In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv("bank.csv")

In [3]:
dataset

age            job   marital  education default  balance housing loan  \
0       59         admin.   married  secondary      no     2343     yes   no   
1       56         admin.   married  secondary      no       45      no   no   
2       41     technician   married  secondary      no     1270     yes   no   
3       55       services   married  secondary      no     2476     yes   no   
4       54         admin.   married   tertiary      no      184      no   no   
5       42     management    single   tertiary      no        0     yes  yes   
6       56     management   married   tertiary      no      830     yes  yes   
7       60        retired  divorced  secondary      no      545     yes   no   
8       37     technician   married  secondary      no        1     yes   no   
9       28       services    single  secondary      no     5090     yes   no   
10      38         admin.    single  secondary      no      100     yes   no   
11      30    blue-collar   married  secondary      no      309     yes   no   
12      29     management   married   tertiary      no      199     yes  yes   
13      46    blue-collar    single   tertiary      no      460     yes   no   
14      31     technician    single   tertiary      no      703     yes   no   
15      35     management  divorced   tertiary      no     3837     yes   no   
16      32    blue-collar    single    primary      no      611     yes   no   
17      49       services   married  secondary      no       -8     yes   no   
18      41         admin.   married  secondary      no       55     yes   no   
19      49         admin.  divorced  secondary      no      168     yes  yes   
20      28         admin.  divorced  secondary      no      785     yes   no   
21      43     management    single   tertiary      no     2067     yes   no   
22      43     management  divorced   tertiary      no      388     yes   no   
23      43    blue-collar   married    primary      no     -192     yes   no   
24      37     unemployed    single  secondary      no      381     yes   no   
25      35    blue-collar    single  secondary      no       40     yes   no   
26      31     technician    single   tertiary      no       22     yes   no   
27      43    blue-collar    single  secondary      no        3     yes   no   
28      31         admin.   married  secondary      no      307     yes   no   
29      28    blue-collar    single  secondary      no      759     yes   no   
...    ...            ...       ...        ...     ...      ...     ...  ...   
11132   32    blue-collar   married  secondary      no     -325     yes  yes   
11133   37     management   married   tertiary      no     1594     yes   no   
11134   58  self-employed   married   tertiary      no     2596      no   no   
11135   36       services  divorced  secondary      no      115      no   no   
11136   31     management    single   tertiary      no        0     yes   no   
11137   49        retired   married    unknown      no      247      no   no   
11138   32     technician   married  secondary      no      235     yes   no   
11139   30  self-employed    single   tertiary      no     2593      no   no   
11140   55       services  divorced  secondary      no     2166     yes   no   
11141   32    blue-collar   married  secondary      no      130     yes   no   
11142   52         admin.  divorced  secondary      no       48      no  yes   
11143   38     unemployed  divorced  secondary      no      189     yes  yes   
11144   60        retired   married  secondary      no        0     yes   no   
11145   60        retired  divorced   tertiary      no     -134      no   no   
11146   30         admin.   married  secondary     yes       23      no  yes   
11147   44     unemployed   married  secondary      no        0      no   no   
11148   32    blue-collar   married  secondary      no        1     yes   no   
11149   46   entrepreneur   married  secondary      no     3317      no   no   
11150  

In [4]:
dataset.head()

age         job  marital  education default  balance housing loan  contact  \
0   59      admin.  married  secondary      no     2343     yes   no  unknown   
1   56      admin.  married  secondary      no       45      no   no  unknown   
2   41  technician  married  secondary      no     1270     yes   no  unknown   
3   55    services  married  secondary      no     2476     yes   no  unknown   
4   54      admin.  married   tertiary      no      184      no   no  unknown   

   day month  duration  campaign  pdays  previous poutcome deposit  
0    5   may      1042         1     -1         0  unknown     yes  
1    5   may      1467         1     -1         0  unknown     yes  
2    5   may      1389         1     -1         0  unknown     yes  
3    5   may       579         1     -1         0  unknown     yes  
4    5   may       673         2     -1         0  unknown     yes

In [5]:
dataset.isnull().any()

age          False
job          False
marital      False
education    False
default      False
balance      False
housing      False
loan         False
contact      False
day          False
month        False
duration     False
campaign     False
pdays        False
previous     False
poutcome     False
deposit      False
dtype: bool

In [6]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11162 entries, 0 to 11161
Data columns (total 17 columns):
age          11162 non-null int64
job          11162 non-null object
marital      11162 non-null object
education    11162 non-null object
default      11162 non-null object
balance      11162 non-null int64
housing      11162 non-null object
loan         11162 non-null object
contact      11162 non-null object
day          11162 non-null int64
month        11162 non-null object
duration     11162 non-null int64
campaign     11162 non-null int64
pdays        11162 non-null int64
previous     11162 non-null int64
poutcome     11162 non-null object
deposit      11162 non-null object
dtypes: int64(7), object(10)
memory usage: 1.4+ MB


In [7]:
x = dataset.iloc[:,0:16]
y = dataset.iloc[:,16:17]

In [8]:
x.shape

(11162, 16)

In [9]:
x = x.values

In [10]:
y = y.values

In [11]:
print(dataset["job"].unique())
print(dataset["marital"].unique())
print(dataset["education"].unique())
print(dataset["default"].unique())
print(dataset["housing"].unique())
print(dataset["loan"].unique())
print(dataset["contact"].unique())
print(dataset["month"].unique())
print(dataset["poutcome"].unique())

['admin.' 'technician' 'services' 'management' 'retired' 'blue-collar'
 'unemployed' 'entrepreneur' 'housemaid' 'unknown' 'self-employed'
 'student']
['married' 'single' 'divorced']
['secondary' 'tertiary' 'primary' 'unknown']
['no' 'yes']
['yes' 'no']
['no' 'yes']
['unknown' 'cellular' 'telephone']
['may' 'jun' 'jul' 'aug' 'oct' 'nov' 'dec' 'jan' 'feb' 'mar' 'apr' 'sep']
['unknown' 'other' 'failure' 'success']


In [12]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [13]:
x[0]

array([59, 'admin.', 'married', 'secondary', 'no', 2343, 'yes', 'no',
       'unknown', 5, 'may', 1042, 1, -1, 0, 'unknown'], dtype=object)

In [14]:
ct = ColumnTransformer([('one', OneHotEncoder(), [1,2,3,4,6,7,8,10,15])], remainder = 'passthrough')
x= ct.fit_transform(x)

In [15]:
x.shape

(11162, 51)

In [16]:
ct1 = ColumnTransformer([('one', OneHotEncoder(), [0])], remainder = 'passthrough')
y= ct1.fit_transform(y)

In [17]:
y

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [18]:
y.shape

(11162, 2)

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size = 0.2,random_state = 0)

In [21]:
print('x shape ', x.shape)
print('y shape ', y.shape)
print('x_train shape ', x_train.shape)
print('x_test shape ', x_test.shape)
print('y_train shape ', y_train.shape)
print('y_test shape', y_test.shape)

x shape  (11162, 51)
y shape  (11162, 2)
x_train shape  (8929, 51)
x_test shape  (2233, 51)
y_train shape  (8929, 2)
y_test shape (2233, 2)


In [22]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [23]:
x_train[0:2,:]

array([[-0.37172192, -0.45760242, -0.17658264, -0.1589378 ,  1.8452729 ,
        -0.27363591, -0.1931085 , -0.30435733, -0.17992689, -0.44212513,
        -0.18025832, -0.08293772, -0.36485864,  0.86351031, -0.66975544,
        -0.39346051,  1.01614555, -0.69993206, -0.21741017,  0.12621015,
        -0.12621015, -1.05825117,  1.05825117,  0.39003722, -0.39003722,
        -1.60273048, -0.27292594,  1.93439945, -0.30193478, -0.39913565,
        -0.09686471, -0.27410848, -0.17488949, -0.39459853, -0.34910544,
        -0.15930776,  1.70870313, -0.30215554, -0.1931085 , -0.16761389,
        -0.35031555, -0.22657536, -0.32939951,  0.58661881,  0.64941897,
        -0.44565283, -0.90504798, -0.2483547 , -0.56394809, -0.48428507,
        -0.35888264],
       [-0.37172192, -0.45760242, -0.17658264, -0.1589378 , -0.54192526,
         3.65449114, -0.1931085 , -0.30435733, -0.17992689, -0.44212513,
        -0.18025832, -0.08293772,  2.7407875 , -1.15806377, -0.66975544,
        -0.39346051,  1.01614

In [24]:
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense

In [25]:
classification = Sequential()

In [26]:
classification.add(Dense(units=51,kernel_initializer='random_uniform',activation='relu'))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [27]:
classification.add(Dense(units=102,kernel_initializer='random_uniform',activation='relu'))

In [28]:
classification.add(Dense(units=102,kernel_initializer='random_uniform',activation='relu'))

In [29]:
classification.add(Dense(units=102,kernel_initializer='random_uniform',activation='relu'))

In [30]:
classification.add(Dense( units=2 , kernel_initializer= "random_uniform", activation="softmax"))

In [31]:
classification.compile(optimizer = "adam", loss = "categorical_crossentropy", metrics=["accuracy"])

In [32]:
classification.fit(x_train, y_train, epochs = 25)

Epoch 1/25
8929/8929 [==============================] - 1s 96us/sample - loss: 0.4425 - acc: 0.7864
Epoch 2/25
8929/8929 [==============================] - 1s 75us/sample - loss: 0.3582 - acc: 0.8508
Epoch 3/25
8929/8929 [==============================] - 1s 77us/sample - loss: 0.3469 - acc: 0.8547
Epoch 4/25
8929/8929 [==============================] - 1s 77us/sample - loss: 0.3341 - acc: 0.8631
Epoch 5/25
8929/8929 [==============================] - 1s 76us/sample - loss: 0.3251 - acc: 0.86520s - loss: 0.3182 - acc: 0
Epoch 6/25
8929/8929 [==============================] - 1s 75us/sample - loss: 0.3196 - acc: 0.8706
Epoch 7/25
8929/8929 [==============================] - 1s 77us/sample - loss: 0.3106 - acc: 0.8729
Epoch 8/25
8929/8929 [==============================] - 1s 75us/sample - loss: 0.3044 - acc: 0.8750
Epoch 9/25
8929/8929 [==============================] - 1s 76us/sample - loss: 0.2990 - acc: 0.8784
Epoch 10/25
8929/8929 [==============================] - 1s 97us/sample - 

In [33]:
ypred = classification.predict(x_test)

In [34]:
ypred

array([[9.9538654e-01, 4.6134242e-03],
       [1.8581582e-03, 9.9814188e-01],
       [9.9994767e-01, 5.2364507e-05],
       ...,
       [2.0388934e-01, 7.9611063e-01],
       [9.8066103e-01, 1.9338934e-02],
       [9.7234917e-01, 2.7650781e-02]], dtype=float32)

In [35]:
ypred = ypred >0.5

In [36]:
ypred

array([[ True, False],
       [False,  True],
       [ True, False],
       ...,
       [False,  True],
       [ True, False],
       [ True, False]])

In [37]:
y_test

array([[1., 0.],
       [0., 1.],
       [1., 0.],
       ...,
       [0., 1.],
       [0., 1.],
       [1., 0.]])

In [38]:
dataset.head()

age         job  marital  education default  balance housing loan  contact  \
0   59      admin.  married  secondary      no     2343     yes   no  unknown   
1   56      admin.  married  secondary      no       45      no   no  unknown   
2   41  technician  married  secondary      no     1270     yes   no  unknown   
3   55    services  married  secondary      no     2476     yes   no  unknown   
4   54      admin.  married   tertiary      no      184      no   no  unknown   

   day month  duration  campaign  pdays  previous poutcome deposit  
0    5   may      1042         1     -1         0  unknown     yes  
1    5   may      1467         1     -1         0  unknown     yes  
2    5   may      1389         1     -1         0  unknown     yes  
3    5   may       579         1     -1         0  unknown     yes  
4    5   may       673         2     -1         0  unknown     yes

In [43]:
x[1]

array([1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0,
       0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 0.0, 1.0, 56, 45, 5, 1467, 1, -1, 0], dtype=object)

In [40]:
yp=classification.predict(sc.transform(ct.transform([[56,'admin.','married','secondary','no',45,'no','no','unknown',5,'may',1467,1,-1,0,'unknown']])))

In [41]:
deposit=["No", "Yes"]

In [42]:
prediction= deposit[np.argmax(yp)]
prediction

'Yes'